name: Terraform code pipeline
 
on:
  push: ['main']
  pull_request: ['main']


jobs:
  init:
    runs_on: ubuntu-latest
    steps:
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v2
      with:
        terraform_version: 1.5.0
    - name: checkout reposotry
      uses: actions/checkout@v2
    - name: initialize 
      run: terraform init
    - name: Terraform Format
      run: terraform fmt -check
    - name: Terraform Validate
      run: terraform validate
    - name: Terraform Plan
      run: terraform plan -input=false
    - name: Terraform Apply
      if: github.ref == 'refs/heads/main' && github.event_name == 'push'
      run: terraform apply -auto-approve -input=false
      environment: production  # Requires manual approval
      run: terraform apply -auto-approve -input=false